services:
  db:
    image: postgres:15
    container_name: skaterbater-db
    restart: always
    ports:
      - "5433:5432"              # Host 5433 → Container 5432
    environment:
      POSTGRES_USER: skateruser
      POSTGRES_PASSWORD: skaterpass
      POSTGRES_DB: skaterdb
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: skaterbater-app
    restart: always
    depends_on:
      - db
    env_file:
      - .env                    # Your .env.local with FLASK_ENV, DATABASE_URL, etc.
    environment:
      # Ensure the app sees the right DB
      DATABASE_URL: "postgresql://skateruser:skaterpass@db:5432/skaterdb"
    ports:
      - "8000:8000"             # Host 8000 → Container 8000 (Gunicorn)
    volumes:
      - .:/app                  # Mount code for live reload in dev

volumes:
  pgdata:
