"""Refactor: replace PracticeSession with PracticeLogEntry

Revision ID: ca2194423a66
Revises: 
Create Date: 2025-06-05 21:48:46.024563

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'ca2194423a66'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trick',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user_trick',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('trick_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['trick_id'], ['trick.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('practice_log_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time_logged', sa.DateTime(), nullable=False),
    sa.Column('tries', sa.Integer(), nullable=False),
    sa.Column('landed', sa.Integer(), nullable=False),
    sa.Column('entries', sqlite.JSON(), nullable=False),
    sa.Column('user_trick_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_trick_id'], ['user_trick.id'], name='fk_logentry_usertrick'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('practice_log_entry')
    op.drop_table('user_trick')
    op.drop_table('trick')
    # ### end Alembic commands ###
