"""Refactor: replace PracticeSession with PracticeLogEntry

Revision ID: efccedac0a15
Revises: ca2194423a66
Create Date: 2025-06-05 22:18:40.270533

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'efccedac0a15'
down_revision = 'ca2194423a66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('practice_log_entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('note', sa.Text(), nullable=True))
        batch_op.drop_column('entries')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('practice_log_entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('entries', sqlite.JSON(), nullable=False))
        batch_op.drop_column('note')

    # ### end Alembic commands ###
